#version 430 core

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer WhitewaterCounterBuffer
{
    uint whitewater_counters[];
};

layout(std430, binding = 1) buffer DrawArgumentsBuffer
{
    uint draw_arguments[];
};

void main(void)
{
    if (gl_GlobalInvocationID.x != 0u)
    {
        return;
    }

    draw_arguments[0] = 4u;
    draw_arguments[1] = whitewater_counters[0];
    draw_arguments[2] = 0u;
    draw_arguments[3] = 0u;
}
